### ISSUE TITLE
Add user callback on struct CanardRxSubscription

### ISSUE THREAD

**Issue by Cherish-forever** [UAVCAN/libcanard#162]
I think CanardRxSubscription need add a function call, named user_callback.

typedef void (*user_callback)(CanardInstance *ins, CanardTransferKind kind, CanardTransfer *transfer);

So that when after receive done, it will call user callback, so user can decode transfer and do something else.

**Comment by pavel-kirienko** [comment]
This would go against some high-integrity coding guidelines that generally prohibit function pointers. We use function pointers for memory allocation/deallocation routines because there is no sensible alternative, whereas what you suggested is adequately covered already by `canardRxAccept()`. If you want a callback-based interface, write a simple wrapper on top of `canardRxAccept()`.
