### ISSUE TITLE
suggestions III

### ISSUE THREAD

**Issue by olliw42** [UAVCAN/libcanard#39]
Hey Pavel
I'm relentless, I know ... some more suggestions

In canard.h I found it useful to change the CanardCANFrame structure to
```
#if CANARD_CAN_FRAME_MAX_DATA_LEN!=8
#  error CANARD_CAN_FRAME_MAX_DATA_LEN must be set to 8
#endif
typedef struct
{
    uint32_t id;
    union{
      uint8_t data[CANARD_CAN_FRAME_MAX_DATA_LEN];
      uint16_t data16[CANARD_CAN_FRAME_MAX_DATA_LEN/2];
      uint32_t data32[CANARD_CAN_FRAME_MAX_DATA_LEN/4];
      uint64_t data64[CANARD_CAN_FRAME_MAX_DATA_LEN/8];
    };
    uint8_t data_len;
} CanardCANFrame;
```
This also allows some code in the stm32 drivers to be cleaned up significantly. I've made a couple of changes in the stm32 driver. You can download my files here: www.olliw.eu/drop/canard_stm32_4pavel_20170410.zip. With a comparison/merge program, like WinMerge, it is very easy to see the changes:
* renamed _internals_bxcan.h to canard_stm32_internals_bxcan.h 
* in struct CanardSTM32CANType; made RF0R,RF1R to RFxR,[2] similar as for other fields
* added support for the iface mode CanardSTM32IfaceModeLoopBack (which I found very useful to get start with)
* mailbox code in canardSTM32Transmit() and canardSTM32Receive() significantly cleaned up
* in some places changed int etc to uint_t etc., and used 16-bit were it deemed appropriate to me

In canard.c allocateBlock() there should be probably an CANARD_ASSERT() to check that the available space is sufficient, i.e. something like allocator->statistics.current_usage_blocks<allocator->statistics.capacity_blocks, similar to the check in freeBlock(), but I was not totally sure what would be correct, hence just this comment.

Cheers, Olli

**Comment by pavel-kirienko** [comment]
Hi Olli, I appreciate your help.

Note that MISRA and other hi rel coding standards do not permit the use of unions. We still have them in the codebase as a matter of deviation, where the code otherwise would be much more complex should we avoid unions altogether. These instances are `CanardPoolAllocatorBlock`, `canardDecodeScalar()`, `canardEncodeScalar()`, `canardConvertNativeFloatToFloat16()`, and `canardConvertFloat16ToNativeFloat()`. Introducing another one into `CanardCANFrame` does not seem to bring much benefit, so we should avoid that change.

> renamed `_internals_bxcan.h` to `canard_stm32_internals_bxcan.h`

OK

> in struct CanardSTM32CANType; made RF0R,RF1R to RFxR,[2] similar as for other fields

Makes sense.

> added support for the iface mode CanardSTM32IfaceModeLoopBack (which I found very useful to get start with)

Perhaps you meant silent loopback mode? Just loopback is mostly useless, since in this mode the controller affects the state of the bus yet can't read from it. If this is so, the mode should be renamed into `CanardSTM32IfaceModeSilentLoopBack`.

> mailbox code in canardSTM32Transmit() and canardSTM32Receive() significantly cleaned up

Great.

> in some places changed int etc to uint_t etc., and used 16-bit were it deemed appropriate to me

Great, as long as this change didn't introduce unnecessary replacements of 8 bit integers with 16 bit types.

> In canard.c allocateBlock() there should be probably an CANARD_ASSERT() to check that the available space is sufficient, i.e. something like allocator->statistics.current_usage_blocksstatistics.capacity_blocks, similar to the check in freeBlock()

`allocateBlock()` requires no additional checks. The one you mentioned from `freeBlock()` is intended to check correctness of the statistics. If the allocator is unable to allocate memory, it returns a null pointer, which the outer code should handle correctly.

Please submit your changes as a pull request. Thank you!
